language: node_js
node_js:
  - "7"
before_script:
  - npm install -g gulp
  - npm install -g nyc
  - npm install -g codecov
script:
  - npm run lint
  - npm run build
  - npm run test-coverage
after_success:
  - npm run coverage
